name : Nodejs Package

on: 
  push: 
   branches: 
    -master

jobs:
  publish-gpr:
   runs-on: macos-latest
   steps:
      - uses: actions/checkout@2
      - uses: actions/setup-node@v1 
        with: 
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@adhishtec'
      - run : npm install
      - run : npm publish
        env :
           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
